//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_WPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class books_db
    {
        public int id { get; set; }
        public string author { get; set; }
        public string title { get; set; }
        public string genre { get; set; }
        public int year_of_publication { get; set; }
    }
}
